name: Build Check on PR

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        example:
          - {name: 'minimal', id: secrets.NETLIFY_SITE_ID_MINIMAL, test: ${{secrets.TEST_SECRET}} }

    steps:
      - uses: actions/checkout@v1
      - name: example/${{ matrix.example.name }}
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          # yarn
          # yarn lerna bootstrap
          # cd examples/${{ matrix.example.name }}
          # NETLIFY_SITE_ID=${{ matrix.example.id }} yarn build
          TEST_SECRET=${{ matrix.example.test }} printenv TEST_SECRET
