name: Deploy Examples

on: [pull_request]
  #push:
  #  branches:    
  #    - master  # Push events on master branch

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        example: ['minimal']
        include:
          - example: minimal
            siteID: ${{ secrets.NETLIFY_SITE_ID_MINIMAL }}

    steps:
      - uses: actions/checkout@v1
      - name: example/${{ matrix.example }}
        env:
          NETLIFY_SITE_ID: ${{ matrix.siteID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          yarn
          yarn lerna bootstrap
          cd examples/${{ matrix.example }}
          yarn build
          npx netlify-cli deploy --dir=public --prod
