name: Deploy Examples

on:
  push:
   branches:    
     - master  # Push events on master branch

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        example:
          - name: 'minimal'
            siteID: 'd196d6a7-ed09-4d96-bb9a-5157b4cf7420'

    steps:
      - uses: actions/checkout@v2
      - run: yarn
      - run: yarn lerna bootstrap
      - name: build example/${{ matrix.example.name }}
        working-directory: examples/${{ matrix.example.name }}
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
        run: yarn build
      - name: deploy example/${{ matrix.example.name }}
        if: success()
        working-directory: examples/${{ matrix.example.name }}
        env:
          NETLIFY_SITE_ID: ${{ matrix.example.siteID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: npx netlify-cli deploy --dir=public --prod --message "${{ github.event.head_commit.message }}"
